### ISSUE TITLE
Make use of PHP 5.6 features

### ISSUE THREAD

**Issue by jrdnull** [exercism/php#12]
As discussed with @wilmoore we should be utilizing the best possible PHP syntax available. When Travis CI supports PHP 5.6 we should update the `Example.php`s to make use of this.

Although I think we should hold back on using 5.6 features in tests as many users will not update asap.

**Comment by petemcfarlane** [comment]
Rather an old issue, but should we be using PHP 7 features now in example files and or test files? Is there a minimum version we have to support?

**Comment by kytrinyx** [comment]
Closing in favor of https://github.com/exercism/php/issues/198 which discusses upgrading to 7.2
