### ISSUE TITLE
Create a getting started page for PHP in the docs repository

### ISSUE THREAD

**Issue by kytrinyx** [exercism/php#19]
See http://help.exercism.io/getting-started-with-go.html as an example.

If appropriate, suggest a linter (see exercism/docs#54).

**Comment by yesroh** [comment]
work on it!

**Comment by kytrinyx** [comment]
Thank you! Also: We changed how we do documentation since we opened this issue.

Now all documentation is in this repository: https://github.com/exercism/xphp/tree/master/docs

This markdown gets sent to the website via an API, and then the website turns it into HTML.

**Comment by kytrinyx** [comment]
We have this documentation now. Closing.
