### ISSUE TITLE
Consider upgrading Travis build and exercises to use PHP 7.2

### ISSUE THREAD

**Issue by kytrinyx** [exercism/php#198]
Currently we support PHP 7.0 on Travis. There's an open pull request upgrading to 7.1—which was quite painless (we just needed to make a couple of small changes to remove warnings).

In order to upgrade to 7.2 we would need to change the `assert()` calls to no longer pass string arguments (see http://php.net/manual/en/function.assert.php).

I'm not sure how common it is for people to have older versions of PHP installed locally, and I don't know how easy it is to upgrade if you have an older version (or how easy it is to understand that you _need_ to upgrade), so I am not necessarily recommending that we upgrade to 7.2, just suggesting that we discuss the trade-offs.

**Comment by petemcfarlane** [comment]
I think it'd be good if we supported at least the latest version (7.2 as of writing), but if we can easily support 7.1 and 7.0 without much trouble that'd be a bonus for people with older version of PHP installed.

Some older machines may have an even older version installed with the OS, but from my experience it's not terribly hard to use a package manager, apt-get, home-brew or the like, to upgrade. It'd be good to gently encourage users to use a more modern version (something that at least has security patches) if they are using an older version.

**Comment by kytrinyx** [comment]
I think at the moment it would be fairly trivial to support both 7.1 and 7.2 on Travis—we can have both in the .travis.yml file.

I'm not sure what it would take to also support 7.0, since the phpunit that gets downloaded doesn't support it.

**Comment by petemcfarlane** [comment]
Ahh ok, we'll just support 7.1/7.2 for now then 👍
