### ISSUE TITLE
PHPUnit Groups

### ISSUE THREAD

**Issue by kunicmarko20** [exercism/php#212]
Hi,

We could start using PHPUnit Groups instead of `$this->markTestSkipped();`

# What would this fix

We don't have to remove `$this->markTestSkipped();` in order to run all tests.

# Example

```
/**
 * @group ignore
 */
public testSomeFunctionality()
{
}
```

To run tests that aren't in group `ignore`:

`phpunit --exclude-group=ignore` 

To run only tests that are in group `ignore`:

`phpunit --group=ignore`

Alternative would be adding to `phpunit.xml`:

```
<groups>
    <exclude>
        <group>ignore</group>
    </exclude>
</groups>
``` 

Which would allow to run just `phpunit` and only tests that don't have `ignore` groupe would run by default.

**Comment by petemcfarlane** [comment]
Interesting, so all the tests would have an `ignore` group apart from the first initial test? Then users would run one group or the other, so they wouldn't have to edit the test file?

Here's another idea - why don't we just remove the `$this->markTestSkipped()` completely, just have the tests failing, so PHPUnit output would look like `......FFFFFFF` as you progressed through the exercise.

I don't know the reason they were marked as skipped originally - maybe to help you focus on one exercise at a time? I can see it is a bit annoying having to manually remove the line of code from each test in the test case though.

**Comment by kunicmarko20** [comment]
> Interesting, so all the tests would have an ignore group apart from the first initial test? Then users would run one group or the other, so they wouldn't have to edit the test file?

Yes, they woudn't need to edit the test file.

I am for removing it also, not sure why was it even added.

>I can see it is a bit annoying having to manually remove the line of code from each test in the test case though.

a bit? 😄

**Comment by petemcfarlane** [comment]
Ok, I'd be happy to approve this, but I don't have time to make the changes right now so if anyone else wants to contribute that would be fantastic 😉 😉

**Comment by kunicmarko20** [comment]
Adding groups or just removing `$this->markTestSkipped()`? I will do it 😄
