### ISSUE TITLE
The link "PHP Security Cheatsheet" in "Useful PHP Resources" has been deleted

### ISSUE THREAD

**Issue by tunggnu** [exercism/php#225]
The link [PHP Security Cheatsheet](https://www.owasp.org/index.php/PHP_Security_Cheat_Sheet) in [Useful PHP Resources](https://exercism.io/tracks/php/resources) has been deleted by OWASP. We should remove them.

**Comment by petemcfarlane** [comment]
Thanks, this has been updated 👍
