### ISSUE TITLE
A fatal error when running Bob tests

### ISSUE THREAD

**Issue by abachi** [exercism/php#230]
Hi,
As said in the title I face a fatal error when I run `bob_test.php`.

Error Message:
`Fatal error: Declaration of BobTest::setUp() must be compatible with PHPUnit\Framework\TestCase::setUp(): void in C:\laragon\www\Exercism\php\bob\bob_test.php on line 156`

PHP version: PHP 7.3.2 (cli) (built: Feb  5 2019 23:14:21)
PHPunit: phpunit-8.0.4.phar
OS: Windows 7

**Comment by DerTee** [comment]
phpunit8 is not supported right now, see #229

**Comment by petemcfarlane** [comment]
We should probably update the tests to support PHPUnit 8, the current version as of the time of writing

**Comment by petemcfarlane** [comment]
@abachi this should be working again now, thanks to @DerTee. Please report if you have any further issues, thanks!
