### ISSUE TITLE
PHP Track - Phone Number Exercise

### ISSUE THREAD

**Issue by mmoray** [exercism/php#260]
The unit tests for the exercise are not built correctly according to the README.md specifications. The N is supposed to be a number between 2 - 9 and the unit tests do not test this and furthermore allow for 0 and 1 for the N number.

**Comment by petemcfarlane** [comment]
Hi @mmoray thanks for raising the issue. You can see the canonical data test file here from the exercism problem specification repository https://github.com/exercism/problem-specifications/blob/master/exercises/phone-number/canonical-data.json

Would you care to create a PR to fix this issue? If not perhaps someone else might like to pick this issue up?

**Comment by arueckauer** [comment]
@petemcfarlane I believe, this can be closed now.
