### ISSUE TITLE
Declaration of supported PHP versions

### ISSUE THREAD

**Issue by arueckauer** [exercism/php#266]
Submitted solutions often show deprecated usage of the language. While they still work, they do not make usage of newer (meaning better) syntax or functionality. Additionally they have become uncommon practice in modern PHP frameworks and libraries.

In order to provide a good experience for students, to learn modern (current) aspects of the language, I recommend defining supported PHP versions. It would clarify supported syntax, especially in regards to type declarations etc.

I am not sure, what the best place for this is, but could imagine the [installation guide](https://exercism.io/tracks/php/installation) as a start. This might be overlooked by those who have PHP already up and running. Maybe you have a better suggestion?

Personally I would prefer the support of currently maintained releases like 7.2 and 7.3. The tests lack some maintenance and could benefit from a dust-off.

For the repository itself and development of it, initializing composer and adding a version constraint for PHP could benefit the process.

Questions:

1. Are there any reasons not to limit supported versions (I might not be aware of)?
2. What is the best place to specify supported versions?

I am curious about the responses and willing to contribute, if changes will be necessary.

**Comment by petemcfarlane** [comment]
I agree it would be wise to encourage learners to update to/use at least a supported (and maintained) version of the language. This will always be in flux, but the repo is probably overdue an update to support 7.2+.

The installation guide seems a sensible place for this (see [source code here](https://github.com/exercism/php/blob/master/docs/INSTALLATION.md])).

We also need to update [travis.yml](https://github.com/exercism/php/blob/master/.travis.yml) too (if we're to officially drop support for PHP 7.1.
