### ISSUE TITLE
Running the tests

### ISSUE THREAD

**Issue by guygastineau** [exercism/php#293]
The `running the tests` link gives the following information:
```
phpunit filename.php
```

This cause a class not found error for me (it seems that `phpunit` is still expecting the classname to match the filename even though a bug report was tagged as fixed from a few years ago).

I was able to make the tests work for `hello-world` by using:
```
phpunit HelloWorldTest hello-world_test.php
```

It would be nice if the doc file were updated to represent this, unless I am missing something trivial that could alleviate the error when used in the recommended manner.

**Comment by khoivan88** [comment]
I put up my finding [here](https://github.com/exercism/php/issues/302#issuecomment-601862179), it is nice to see another solution!
