### ISSUE TITLE
Recruiting additional maintainers for PHP

### ISSUE THREAD

**Issue by kytrinyx** [exercism/php#299]
We're about to start a big push towards version 3 (v3) of Exercism. This is going to be a really exciting step forward for Exercism, with in-browser coding, new Concept Exercises with automated feedback, improved mentoring and much more.

This to be a big community effort, with the work spread out among hundreds of volunteers across Exercism. One key thing is going to be each track having enough maintainers who have the time to manage that community effort. We are therefore putting out a call for new maintainers to bolster our numbers. We're hoping that our existing maintainers will be able to act as mentors to the newer maintainers we add, and take on a parental role in the tracks.

If you are an existing maintainer, could you please reply to this letting us know that you think you'll have time (2-3hrs/week) to help with this over the next 6 months. If you won't have that time, but still want to be a maintainer and just help where you can instead, please tell us that too. If you have come to the end of the road as a maintainer, then we totally understand that and appreciate all your effort, so just let us know.

For anyone new who's interested in becoming a maintainer, thanks for your interest! Being an Exercism maintainer is also a great opportunity to work with some other smart people, learn more about your language of choice, and gain useful skills and experience that are useful for growing your career in the technical leadership direction. Please write a comment below introducing yourself along with your Exercism handle, and telling us why you're interested in becoming a maintainer, and any relevant experience. We will then evaluate every application and contact you using your exercism email address once we have finished the evaluation process.

Thank you!

See also https://github.com/exercism/exercism/issues/5161

**Comment by James-N-M** [comment]
## Intro 😄 
Hey I'm James 🇨🇦 🌉, I'm 25 and have been writing php for our older applications and using the Laravel Framework for our new applications professionally for almost 2 years at Flex N Gate we build a Program Life Cycle management Tool (I promise we didn't build that ugly looking website) . I came to Exercism looking to improve my php skills. I felt like I had a good handle on Laravel but never used php in university. So I had never used it to solve any trivial programming problems. 

## Why ❓ 
I'm interested in becoming a maintainer, mostly to be part of the squad and form some new relationships while building stuff that a ton of people are gonna use. I helped work on a few open source projects in the past and it was always cool showing my fellow co workers and friends stuff and be able to say I helped build that thing. 

## OSS Experience 💥 
I built a theme switcher for https://github.com/Protoqol/Prequel , made a simple laravel provider https://github.com/James-N-M/faker-pokemon , took part in Hacktoberfest two years in a row contributing to agorakit and goodwork.

**Comment by ashishkpoudel** [comment]
Hi i'm Ashish https://exercism.io/profiles/ashishkpoudel. I am 26 year old PHP developer having 3 years of experience. Mostly i work with Laravel in my day job. I signed up for exercism today and somehow i landed here. I'm interested in being part of this journey.

**Comment by 0x647262** [comment]
Count me in!

**Comment by iHiD** [comment]
@0x647262 Thanks :) How about working on these two issues to get started:

- https://github.com/exercism/php/issues/323
- https://github.com/exercism/php/issues/322

**Comment by ErikSchierboom** [comment]
@ashishkpoudel @0x647262 If you send an email to erik @ exercism.io, I can help you get started on contributing!

**Comment by James-N-M** [comment]
@ErikSchierboom Will do ! I could use a hand getting started :)

**Comment by ErikSchierboom** [comment]
We're closing this issue as it was part of our push to implement the v3 version of this track and v3 has [just been released](https://exercism.org/blog/exercism-v3-has-launched).

New maintainer are always welcome though!
