### ISSUE TITLE
Gigasecond exercise improvements

### ISSUE THREAD

**Issue by meganos** [exercism/php#301]
I am a mentor on the PHP track. I’ve noticed that some students are having trouble with the gigasecond track -- it’s not obvious to them what they should call their function. I should note that if you _do_ attempt to run the test suite, it does complain that there are calls to an undefined function `from`. However,  there are some submissions where students have expressed that they don't know what to call the function and then later they figure it out, or they submit iterations with a different function name. I am wondering if we can improve on this? 

Maybe we could add more information to the stub file https://github.com/exercism/php/blob/master/exercises/gigasecond/gigasecond.php that the function should be called `from`?

The `README` instructions copy could also be expanded e.g. currently it's

```
You must add a gigasecond to the informed date.

A gigasecond is 10^9 (1,000,000,000) seconds.
```

**Comment by kotp** [comment]
Is this a mentoring moment, where the student doesn't understand what the error message is telling them, and this is an opportunity to bring that to their attention?  If we make it explicitly instructed in the README, does it diminish their ability to troubleshoot when it comes time to do so?

**Comment by meganos** [comment]
It’s one of the early exercises so I was thinking perhaps a skeleton file could potentially be beneficial like we have for the second core exercise, [Hamming](https://github.com/exercism/php/blob/master/exercises/hamming/hamming.php).

Part of the learning process is of course the student troubleshooting and arriving at the conclusion that a `DateTimeImmutable` object must be a parameter for this exercise. It seems like some students submit without running the test suite so they don’t realize that this particular object needs to be used or what the function should be named.  Students are permitted to submit incomplete solutions, so I will continue to help out with and highlight how running the test suite is helpful to arrive at an optimal solution.

**Comment by kotp** [comment]
On Mon, Mar 16, 2020 at 08:39:26AM -0700, meganos wrote:
> It’s one of the early exercises so I was thinking perhaps a skeleton
> file could potentially be beneficial like we have for the second core
> exercise,
> [Hamming](https://github.com/exercism/php/blob/master/exercises/hamming/hamming.php).

As you linked to the skeleton fle in a prior message, I think it is
already there.

> Part of the learning process is of course the student troubleshooting
> and arriving at the conclusion that a `DateTimeImmutable` object must
> be a parameter for this exercise. It seems like some students submit
> without running the test suite so they don’t realize that this
> particular object needs to be used or what the function should be
> named.

Maybe the comment that we find in that hamming skeleton file could be
applied to all of the exercise files?  I did something similar for the
Ruby track.  (And then the common complaint is stale comments being left
in the file, after the student does the things mentioned in the
comments).  Perhaps double check that the REAMDE has the necessary
information as well.

> Students are permitted to submit incomplete solutions, so I
> will continue to help out with and highlight how running the test
> suite is helpful to arrive at an optimal solution.

This is definitely something I do as well in the early exercises for
some students, so it benefits them, and hopefully avoids that
conversation in later exercises.

**Comment by neenjaw** [comment]
Function stub is now provided in the newest version. Closing.
