### ISSUE TITLE
Can't Run Hello World Tests On Mac

### ISSUE THREAD

**Issue by JimLynchCodes** [exercism/php#302]
Hi, I'm using a mac OS 10.15.3

I have installed php and phpunit via brew:
```
PHPUnit 9.0.1 by Sebastian Bergmann and contributors.
PHP 7.4.3 (cli) (built: Feb 20 2020 12:23:10) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies
```

However, when I run `phpunit ./hello-world.php` or `phpunit ./hello-world_test.php` I just get errors that the file cannot be found.

When I try to run the command listed in the README, `./phpunit.phar hello-world/hello-world_test.php`, it gives me this error:
```
-bash: ./phpunit.phar: No such file or directory
```

It would be great if someone could help me out and update the hello world exercise README with the correct command. Thanks! 🙏

**Comment by petemcfarlane** [comment]
Hi Jiim, how did you get that phpunit version to print out, did you run `./phpunit.phar --version` or  just `phpunit --version`? If the later, can you try running `phpunit ./hello-world_test.php` instead?

**Comment by JimLynchCodes** [comment]
Thanks @petemcfarlane!

I ran `phpunit --version` to get the output. 

When I run `./phpunit.phar --version` I get the error:
```
-bash: ./phpunit.phar: No such file or directory
```

When I try running `phpunit ./hello-world_test.php` I get this error:
```
Class 'hello-world_test' could not be found in '/Users/jim/Exercism/php/hello-world/hello-world_test.php'.
```

Not sure why it is trying to look for the class `hello-world_test` when in the file the class name is `HelloWorldTest`...

**Comment by khoivan88** [comment]
I believe this is the phpunit 9 issue. I have the same issue with phpunit 9 on Ubuntu and Windows (for both downloaded phpunit.phar and composer install). phpunit 8 and 8.5 works for me on Windows and ubuntu (phpunit 6.5 also works on ubuntu)

**Comment by JimLynchCodes** [comment]
thanks @khoivan88! 

Not sure how I can downgrade phpunit on mac though... 🤔

**Comment by khoivan88** [comment]
Maybe this might help? https://stackoverflow.com/questions/49368707/homebrew-how-do-i-install-phpunit-6-5/50165105
Otherwise, i know composer can install specifically version so maybe you can use Homebrew to install composer then use composer to install 8.5?

**Comment by JimLynchCodes** [comment]
Thanks @khoivan88! - 

I'm still confused though... what exactly are you recommending?

I tried all three, but they all give the error that it can't be found...

`brew install phpunit@8.5`
`brew install phpunit@8`
`brew install phpunit@6.5`

![Screen Shot 2020-03-24 at 3 09 50 PM](https://user-images.githubusercontent.com/5354163/77466984-8387b680-6de1-11ea-8980-d3b1cc79c0f4.png)

**Comment by khoivan88** [comment]
@JimLynchCodes



Based on the error above, it looks like brew cannot install other phpunit. Could you try installing composer using brew? Then `cd` into your project folder, in this case, likely `Users/your-username/exercism/php` and then use `composer require --dev phpunit/phpunit ^8.5`
Then confirm the php unit with
```bash
vendor/bin/phpunit --version
```

If that says 8.5.x then i think you are good to go:
```bash
vendor/bin/phpunit path/your_php_test_file.php
```

**Comment by JimLynchCodes** [comment]
Thank you @khoivan88!

After using composer I was able to successfully run the tests with phpunit 8.5! ♥️
