### ISSUE TITLE
Updating the PHP track

### ISSUE THREAD

**Issue by neenjaw** [exercism/php#310]
A big problem with the PHP track as it is, is that the installation instruction and the instructions to run the tests don't work. They require students to deduce the problem, and more likely, frustrates them to not try. Let's fix this:

### Step 1: Quick fix

Change the install and run the test instructions to direct the students to download the newest version of phpunit version 8.  Version 9 introduced a breaking change that the current test suite does not work on.

So this requires a change to the documentation.

### Step 2: Future fix

So thinking about the future, PHPunit being version 9 now and version 10 in 2021, This should likely be tackled, but is a bit more work.

- Test files will need to be renamed to reflect the test class name.
- This may require further changes
- Then the instructions can be reverted or changed to instruct students to install the newest version of phpunit v9

---

I am willing to do this work, and I will start with the first step if that is alright within the next week.

Unless there is significant disagreement, I'll take it as a sign to go ahead with the plan.

**Comment by petemcfarlane** [comment]
Thanks this would be great if you would like to make a start @neenjaw!
