### ISSUE TITLE
Exercise stubs

### ISSUE THREAD

**Issue by neenjaw** [exercism/php#347]
Many exercises don't have stubs.  For example Gigasecond is an empty file, but it should have a stub defined like:

```php
// gigasecond.php
<?php

function from(DateTimeImmutable $date) {
    throw new Exception('Not implemented');
}
```

This will lead to a better experience using the website code editor and also help to define the sandbox of solutions for students.

**Comment by codedge** [comment]
Is that something where I can through the exercises and check? [Here](https://github.com/exercism/php/pull/351#discussion_r598207310) we used a `BadFunctionCallException`

```php
<?php

function xyz(int $number): string {
  throw new \BadFunctionCallException("Implement the xyz function");
}
```

So can we agree on using this exception throughout all the stubs?

**Comment by neenjaw** [comment]
In exercises that are just functions, yes, I think that exception is the proper one to use (PHP doesn't have a native `NotImplementedException` and I would like to keep exercises simple).  For exercises which require a class (I'm not sure which ones off-hand) it should probably be something like:

```php
<?php

class ExampleClass
{
    public function doSomething(): int
    {
        throw new \BadMethodCallException("Implement the doSomething method");
    }
}
```

**Comment by neenjaw** [comment]
Fulfilled by #357
