### ISSUE TITLE
Duplicate UUIDs for `resistor-color` and `simple-cipher`

### ISSUE THREAD

**Issue by ee7** [exercism/php#404]
Each UUID should be unique Exercism-wide, but the below UUIDs

https://github.com/exercism/php/blob/e6b7263a19b93dfc44a3661248855daec2a16d14/config.json#L52-L54

https://github.com/exercism/php/blob/e6b7263a19b93dfc44a3661248855daec2a16d14/config.json#L89-L91

already existed on the Javascript track:
- https://github.com/exercism/javascript/blob/98fbe3e47747/config.json#L231-L233
- https://github.com/exercism/javascript/blob/98fbe3e47747/config.json#L399-L401

`configlet lint` currently only checks for duplicate UUIDs **within** the track, so CI doesn't catch this - sorry.

(Note that even if `configlet lint` gains that ability, CI will still pass for two PRs that add the same UUID if they are open simultaneously on different tracks).

**Comment by MichaelBunker** [comment]
Is there an easy way to check UUIDs between tracks? I just used an online UUID generator for them when I added the PRs for these exercises and just checked the PHP config for conflicts, but didn't think to check other tracks.

With 50+ tracks it's a bit of a hassle to check them all. Are the UUIDs compiled to a single file somewhere that I can check or do I need to look at each repository?

**Comment by MichaelBunker** [comment]
Actually looking at the pull requests, they were two stale PRs that I just updated for the new directory structure and I assumed the PHP UUIDs were already unique, so it looks like it was just a simple copy paste problem from the original PRs that got stale. I can update them both to be unique since it doesn't appear that they were randomly generated UUIDs, though it will be nice if there was a way for me to be able to tell this is an issue in the future if the CI won't catch it.

**Comment by ee7** [comment]
> Is there an easy way to check UUIDs between tracks?

Currently, the easiest ways are:
- `git clone` every track
- or download every `config.json`
- or use GitHub search

But we just need to make sure that each new UUID isn't copy-pasted from an already-existing one on Exercism. If it's generated randomly, there's no meaningful chance of a collision because the number of possible UUIDs is so large. 

From [Wikipedia](https://en.wikipedia.org/wiki/Universally_unique_identifier#Collisions):
> [there are] 5.3×10^36 (5.3 undecillion) possible version-4 variant-1 UUIDs

> the number of random version-4 UUIDs which need to be generated in order to have a 50% probability of at least one collision is 2.71 quintillion [...] This number is equivalent to generating 1 billion UUIDs per second for about 85 years.

> the probability to find a duplicate within 103 trillion version-4 UUIDs is one in a billion.

**Comment by ee7** [comment]
> it will be nice if there was a way for me to be able to tell this is an issue in the future

The plan is that `configlet lint` will eventually catch this at CI-time. And that if a bad UUID is somehow added regardless, the website will refuse to sync and automatically open an issue on the track.

**Comment by MichaelBunker** [comment]
I've checked the other PRs I have open to make sure they aren't copy pasted UUID and they all seem unique (No results searching on Github). If I update abandoned PRs again in the future I'll make sure to check the UUIDs are unique.

Thanks for the explanation and sorry about the hassle this caused.
