### ISSUE TITLE
Submitting customized tests

### ISSUE THREAD

**Issue by arueckauer** [exercism/php#413]
Adjustments to the original tests are necessary e.g., if the class under test is placed in a namepsace.

Is it possible to have the test engine run submitted tests instead of the original one?

**Comment by neenjaw** [comment]
As far as I know, no there is no current plan to allow submitted test files to be used in place of the canonical ones. 

Is it possible, yes, but it would be exceptional and this would probably be a product decision. @iHiD / @ErikSchierboom

**Comment by ErikSchierboom** [comment]
> Is it possible to have the test engine run submitted tests instead of the original one?

There are no plans, as this would allow students to just rewrite tests if their implementation does not pass them. This would make mentoring a lot harder too, as you can't rely on on "knowing" the test suite. 

> Adjustments to the original tests are necessary e.g., if the class under test is placed in a namepsace.

I don't exactly understand this comment. Are there exercises where you'd _have_ to change the tests? Do you have any examples?

**Comment by arueckauer** [comment]
@ErikSchierboom I agree. Changing tests adds complexity for the reviewing process of a mentor as well as the automated tests.

I just like to add strictness and clarity to my tests by adding type declarations and putting functions for example in a namespace. So, it is more a personal preference and nothing where changes must be changed.

I close this for the moment as I feel this is not a common request. Thanks for your responses!
