### ISSUE TITLE
Automated formatting for PHP code files

### ISSUE THREAD

**Issue by neenjaw** [exercism/php#418]
Looking for input.  Not disagreeing with people having a personal preference of one style over the other, but what do you think of implementing some sort of automated formatting that can be used to consistently (and automatically) apply a style to the code base? We can then also implement CI to lint against this.

Some potential solutions:
- prettier-php (https://github.com/prettier/plugin-php) -- not sure how I feel about having to add yarn as a dependency in a php repo
- php-cs-fixer (https://github.com/FriendsOfPHP/PHP-CS-Fixer)
- phpfmt (https://github.com/kodeclan/phpfmt)

Thoughts? Opinions?

**Comment by neenjaw** [comment]
@arueckauer @petemcfarlane @dstockto

**Comment by neenjaw** [comment]
Yea, I have no experience with things other than php-cs-fixer, but just wanted to put out there that open to alternatives if better things exist.  If was have a start with php cs fixer, building on that might be an easy win to implement this.

**Comment by petemcfarlane** [comment]
Sounds good, I’ve used php-cs-fixer and php CodeSniffer - both on the same project at times, although I wouldn’t recommend this because in edge cases they sometimes contradict each other and cause more headaches. 
Whichever standard I recommend it a superset of PSR12.

**Comment by neenjaw** [comment]
Since we have phpcs in our CI already, I spun up a draft pr with the laminas coding standard rules added.  Quite a few rules I think we would have to disable (just due to project requirements -- e.g. the example solution being named different from the inner class). But was super simple.

Draft PR here: #421

**Comment by arueckauer** [comment]
@neenjaw Awesome!

Gobally I exclude the `PSR1.Methods.CamelCapsMethodName` rule for test classes. Descriptive test method names can be rather long and I write them in snake_case for improved readability. Other than I only add exclusions for legacy code, where the coding standard can not be applied all at once.

As for this project, there are quite a few errors that could be fixed automatically. While it is possible to ignore or disable phpcs for specific lines in a file, I would suggest having all these rules in the phpcs configuration file thus not confusing users with irrelevant coding style directives.

**Comment by homersimpsons** [comment]
It looks like this issue is solved with:
- https://github.com/exercism/php/blob/main/.github/workflows/exercise-lint-phpcs-psr-12.yml
- https://github.com/exercism/php/blob/main/phpcs-php.xml

@neenjaw Should it be closed ?

**Comment by neenjaw** [comment]
> It looks like this issue is solved with:
> 
> - https://github.com/exercism/php/blob/main/.github/workflows/exercise-lint-phpcs-psr-12.yml
> 
> - https://github.com/exercism/php/blob/main/phpcs-php.xml
> 
> 
> 
> @neenjaw Should it be closed ?

As @arueckauer said above:

https://github.com/exercism/php/issues/418#issuecomment-952792656

This issue has not been fulfilled by the existing psr12 linting standard. 

However since I haven't continued with this and no one else has, we can close it.

**Comment by homersimpsons** [comment]
> [#418 (comment)](https://github.com/exercism/php/issues/418#issuecomment-952792656)

Oh sorry I did not read this comment. To me we should stick to PSR12 for as this is the only widely accepted coding standard.

Personally I like https://github.com/doctrine/coding-standard (with some tweaks)
