### ISSUE TITLE
Poker exemplar does not rank two-pairs correctly

### ISSUE THREAD

**Issue by dstockto** [exercism/php#454]
I am not sure if I should start this in the canonical data or if it's just an issue with the PHP exemplar. The exemplar calculates a score using 200 + the rank of both pairs (one face value of one pair, plus one face value of the other) and then uses the final card as a leftover. The problem is that by just adding the two different paired faces, it will incorrectly drop down to using the kicker (the leftover card). It should only be considering the kicker if the two pairs of each hand are the same value.

For example, the examplar treats these two hands as a tie:
- 6S,6H,3S,3H,AS
- 7H,7S,2H,2S,AC

Since 6+3 = 7+2, the Ace kicker is what is being evaluated, but it should rank the 7s and 2s as the winner.

I have code with another test and an updated examplar, but I don't know if I should be adding this test case to the canonical data first. Please let me know.

**Comment by dstockto** [comment]
I went ahead and PR'd to the problem-specifications first: https://github.com/exercism/problem-specifications/pull/2001

**Comment by neenjaw** [comment]
I think you've handled this the right way. I would go so far to say that the example solutions are often more proofs that it is solvable rather than the best example of solution in that language. 

Do you want me to review this now or wait until you've added the test cases from the discussion in problem specs?

**Comment by dstockto** [comment]
I have a branch with the new test case. Actually, test cases as there was another one suggested that I added as well. I have the approvals, but I think it needs to be merged. Once it's merged, I'll PR those new test cases and a modification to the example code.

**Comment by dstockto** [comment]
Closed with #453
