### ISSUE TITLE
Confusing Instructions

### ISSUE THREAD

**Issue by FayeDM** [exercism/php#589]
Admittedly, I really struggle with written instructions. I have a hard time visualizing them (dyscalculia) and I can't parse what I'm being asked to do, especially if I feel like the instructions and the task don't align. I know this is a mind numbingly easy task (I'm a WP developer, I've been using php for 10 years) but I got stuck because I hit a cognitive roadblock.

> The classical introductory exercise. Just say "Hello, World!".
> 
> ["Hello, World!"](https://en.wikipedia.org/wiki/%22Hello,_world!%22_program) is the traditional first program for beginning programming in a new language or environment.
> 
> The objectives are simple:
> 
> Write a function that returns the string "Hello, World!".
> Run the test suite and make sure that it succeeds.
> Submit your solution and check it at the website.
> If everything goes well, you will be ready to fetch your first real exercise.

So the problem here is it says "Write a function" and I was using the online editor and it had a function already for Goodbye something. And I couldn't understand...like it took me a dumb amount of time just to replace the "Goodbye" string with Hello World, because I thought I was supposed to write something new.

Also - I just echo'd out the hello world in my attempt because...that's a function? Isn't it? It does the thing...anyway. For those with learning disabilities, just some "stating the obvious" clarity would be nice.

**Comment by neenjaw** [comment]
This exercise is based on an [upstream specification](https://github.com/exercism/problem-specifications/tree/main/exercises/hello-world), so I can't make any changes here.  However, your point is worth discussing on [our forum](https://forum.exercism.org/) such that awareness can be made around the issue and improvements to it can be suggested.

I would strongly suggest copying and pasting this issue into a forum discussion to get this looked at by the larger group to see if solutions to some of the gaps can be explored.

**Comment by FayeDM** [comment]
Oh thank you! I wasn't sure where to put the thought, I struggled to find a feedback or a submission something, I will hop over to the forum!

**Comment by neenjaw** [comment]
Awesome! Thanks for doing that, I'm going to close this issue here so that it can be discussed on the forum! 🎉
