### ISSUE TITLE
Re-enable testing on MacOS

### ISSUE THREAD

**Issue by mk-mxp** [exercism/php#645]
Due to an issue out of our control testing on PHP8.1+ with MacOS 12 always fails. Enable it again (I commented it out) when https://github.com/shivammathur/setup-php/issues/823 is fixed.

The issue is fixed, but should we really enable it again? See https://forum.exercism.org/t/php-stop-running-ci-tests-on-macos-and-windows/10025

**Comment by tomasnorre** [comment]
I have created a PR that works with `macOS-13`. 

https://github.com/exercism/php/pull/646

**Comment by mk-mxp** [comment]
As discussed on the forum, the testing with MacOS and Windows will go on. Currently looking for the best version of MacOS to tie the workflow to. `macos-latest` was and is `macos-12`, but there is `macos-13` and `macos-14` available, too.

**Comment by tomasnorre** [comment]
Which one should we aim for? I can create the PR again.

**Comment by mk-mxp** [comment]
@tomasnorre Please use `macos-12` for re-making the PR. Thank you!
