### ISSUE TITLE
#48in24: Meetup 2024-08-20 and PHP is a featured language

### ISSUE THREAD

**Issue by mk-mxp** [exercism/php#667]
`Meetup` will be the only exercise with PHP as featured language during `#48in24`! Let's prepare it well:

- [x] Run `bin/configlet sync -u -e meetup --yes --docs --filepaths --metadata --tests include` (updates the Markdown files and maybe `tests.toml`)
  - docs: instructions unsynced: meetup
  - metadata: unsynced: meetup
- [x] Drop strict types comments from test file and example code (these are useless)
- [x] Add and sync test meta data to tests (`uuid` / `@testdox` in DocBlocks)
- [x] Decide on adding / adjusting / ordering test cases to match current problem specs

Do not redesign the student's interface or add test cases that would invalidate existing community solutions. These are extra tasks, which should be discussed in advance.

In addition to the other sync-ing tasks, consider doing these:

- [ ] Polish the tests to be really readable (e.g. add failure messages to assertions)
- [ ] #617 
- [ ] Go through the track docs and update installation instructions, help resources etc.
- [ ] Add [approaches](https://exercism.org/docs/building/tracks/approaches) and [articles](https://exercism.org/docs/building/tracks/articles)

**Comment by sarad1p1ty** [comment]
Hi,
If this is the featured task for next week, I could have a look today/tomorrow?

**Comment by mk-mxp** [comment]
@sarad1p1ty Yes, you are welcome! The first 4 checkpoints are some kind of minimum points to have (but there might be nothing to do). And hopefully there are no surprises in the 4th point.

The data for UUID, `@testdox` nice test name and the 4th point is taken from this file: https://github.com/exercism/problem-specifications/blob/main/exercises/meetup/canonical-data.json

To locally test against the changed test cases, you may copy the example.php contents into the student stub `Meetup.php` and run PHPUnit against it: `vendor/bin/phpunit --no-configuration --do-not-cache-result exercise/practice/meetup/MeetupTest.php`. Or use `composer ci` if you solved the problems you had with that.

In case of any trouble: I do have little time until Monday. But I'll do my very best to answer all questions.

**Comment by sarad1p1ty** [comment]
That's really helpful. Thank you!
I will let you know if I run into any problems.
