### ISSUE TITLE
#48in24: minesweeper 2024-05-14

### ISSUE THREAD

**Issue by mk-mxp** [exercism/php#692]
- [x] Run `bin/configlet sync -u -e minesweeper` (updates the Markdown files and maybe `tests.toml`)
  - docs: instructions unsynced: minesweeper
  - docs: introduction missing: minesweeper
  - metadata: unsynced: minesweeper
- [x] Drop strict types comments from test file and example code (these are useless)
- [x] Add and sync test meta data to tests (`uuid` / `@testdox` in DocBlocks)
- [x] Decide on adding / adjusting / ordering test cases to match current problem specs

Do not redesign the student's interface or add test cases that would invalidate existing community solutions. These are extra tasks, which should be discussed in advance.

Replaces #686

**Comment by mk-mxp** [comment]
@homersimpsons FYI: This exercise is so far away from problem specifications, syncing it will result in a new exercise. It seems like it wasn't sync'ed for Exercism V3...

The main difference is, that PHP track expects a border (with border completeness validation) around the board. This is not mentioned in instructions and not part of tests in problem spec.

If you don't object to this, I'll come up with the PR on the weekend.

**Comment by homersimpsons** [comment]
> If you don't object to this, I'll come up with the PR on the weekend.

Looks like there are only 19 published solutions on https://exercism.org/tracks/php/exercises/minesweeper/solutions so yes let's clean it up just like #694
