### ISSUE TITLE
exercises/concept/language-list/LanguageListTest.php testLanguageListCount incorrect

### ISSUE THREAD

**Issue by kharris-tsc** [exercism/php#716]
The current assertion will allow an empty function to pass.
This should be corrected to get the return from the function call and assert that return is equal to the length of the list provided.

**Comment by mk-mxp** [comment]
Hi @kharris-tsc, welcome to the PHP track!

Thanks for reporting this. I see your point. The test is only checking, that `language_list_length()` does not mutate the original list. So the test should be `testLanguageListCountDoesNotMutate()`. And there should be an additional test `testLanguageListCount()` that actually checks the result of `language_list_length()`.

Are you willing to adjust your Pull Request for this?

**Comment by kharris-tsc** [comment]
@mk-mxp I updated the current test to check what is returned, if you are suggesting I add a test for the mutation I can it next.

**Comment by mk-mxp** [comment]
Yes, the additional test would be great. Thanks in advance!

**Comment by kharris-tsc** [comment]
@mk-mxp I added this additional test case and ran it against my current solution locally

![image](https://github.com/exercism/php/assets/165825248/e31bf483-ecb4-4d42-bb21-d06ed0512883)

**Comment by mk-mxp** [comment]
Thank you for improving the PHP track!
