### ISSUE TITLE
#48in24: rna-transcription 2024-06-25

### ISSUE THREAD

**Issue by mk-mxp** [exercism/php#730]
- [x] Run `bin/configlet sync -u -e rna-transcription --yes --docs --filepaths --metadata --tests include` (updates the Markdown files and maybe `tests.toml`)
  - metadata: unsynced: rna-transcription
- [x] Drop strict types comments from test file and example code (these are useless)
- [x] Add and sync test meta data to tests (`uuid` / `@testdox` in DocBlocks)
- [x] Decide on adding / adjusting / ordering test cases to match current problem specs

Do not redesign the student's interface or add test cases that would invalidate existing community solutions. These are extra tasks, which should be discussed in advance.

**Comment by fejan92** [comment]
Running bin configlet command will update the config.json file and I think there is something wrong with source_url.
Please confirm this. Thanks!

config.json
```json
{
  "authors": [],
  "contributors": [
    "arueckauer",
    "dkinzer",
    "kunicmarko20",
    "kytrinyx",
    "lafent",
    "petemcfarlane"
  ],
  "files": {
    "solution": [
      "RnaTranscription.php"
    ],
    "test": [
      "RnaTranscriptionTest.php"
    ],
    "example": [
      ".meta/example.php"
    ]
  },
  "blurb": "Given a DNA strand, return its RNA Complement Transcription.",
  "source": "Hyperphysics",
  "source_url": "https://web.archive.org/web/20220408112140/http://hyperphysics.phy-astr.gsu.edu/hbase/Organic/transcription.html"
}

```

**Comment by mk-mxp** [comment]
@fejan92

If you ran the `configlet` command, all files are updated according to a common source for problem statements, called [problem specifications](https://github.com/exercism/problem-specifications). This is our "source of truth" for the markdown files, `config.json` and the tests we will use (listed in `.meta/tests.toml`).

Please don't change anything in the markdown files. `~~~~exercism/notes` is a marker string specific to exercism and valid markdown. It is not just a code block.

The links in markdown or `config.json` are chosen by Exercism staff. If it is not working (you can't open it in your browser or the page you get is nothing about the exercise), report that in [problem specifications](https://github.com/exercism/problem-specifications). In this case: The web archive project is a well known not-for-profit service helping against internet volatility - they store and deliver web pages from the past.

Just re-run the sync command and commit everything it changes - that's what we expect to get.

**Comment by mk-mxp** [comment]
For most community solutions, adding the empty string test was no problem. I only found one cheaty solution that will fail. And more than 50% of the solutions are outdated anyways (file name changed long time ago).
