### ISSUE TITLE
#48in24: Sync leap

### ISSUE THREAD

**Issue by mk-mxp** [exercism/php#739]
- [x] Run `bin/configlet sync -u -e leap --yes --docs --filepaths --metadata --tests include` (updates the Markdown files and maybe `tests.toml`)
- [x] Drop strict types comments from test file and example code (these are useless)
- [x] Add and sync test meta data to tests (`uuid` / `@testdox` in DocBlocks)
- [x] Decide on adding / adjusting / ordering test cases to match current problem specs

Do not redesign the student's interface or add test cases that would invalidate existing community solutions. These are extra tasks, which should be discussed in advance.

**Comment by mk-mxp** [comment]
@fejan92 You may start here... :smiley: Happy Coding :computer:

**Comment by fejan92** [comment]
Sure soon I will work on this.
Thanks!
