### ISSUE TITLE
Missing semicolon in the "Classes" section

### ISSUE THREAD

**Issue by Anoushka-0410** [exercism/php#751]
The second example has a missing semicolon in the line "public $color". It can be misleading for beginners.

**Comment by mk-mxp** [comment]
Hi @Anoushka-0410 welcome to the PHP track!

Could provide a link to the page with the "Classes" section you refer to?

Thank you!

**Comment by Anoushka-0410** [comment]
Sure! Here you go
https://exercism.org/tracks/php/concepts/class-basics

**Comment by mk-mxp** [comment]
Found [here](https://github.com/exercism/php/blob/4f5b55daa8df90ae15355c184e55826880ab1775/concepts/class-basics/introduction.md?plain=1#L45), [here](https://github.com/exercism/php/blob/4f5b55daa8df90ae15355c184e55826880ab1775/concepts/class-basics/about.md?plain=1#L45), and [here](https://github.com/exercism/php/blob/4f5b55daa8df90ae15355c184e55826880ab1775/exercises/concept/windowing-system/.docs/introduction.md?plain=1#L47)

Will get fixed soon...

**Comment by Anoushka-0410** [comment]
Thank you!
