### ISSUE TITLE
Annalyns Infiltration - Task 4 - Instructions don't match tests

### ISSUE THREAD

**Issue by mk-mxp** [exercism/php#758]
In [this forum thread](https://forum.exercism.org/t/bug-in-annalyns-infiltration-test/11705) we discovered, that there ~~is~~ seemed to be a mismatch between the instructions (top part, not the task description itself) and the test cases we have.

As this is a well-accepted concept exercise solved by many students, we should rather ~~change the instructions~~ extract the logic from them and check, if we need to update the instructions.

- [x] Add a logic table (inputs and expected result) to `exercises/concept/annalyns-infiltration/.meta/design.md` to ensure proper wording of instructions for the future
- [x] ~~Find wording that matches the logic of the tests~~
- [x] Order tests to follow the sequence of instruction conditions (e.g. the first statement is "If Annalyn has her pet dog with her" -> first all tests "with dog" then all tests "without dog")
- [x] Ask in forum about wording and logic issues of the new version
- [x] Rename exercise title to `Annalyn's Infiltration` (apostrophe added)

**Comment by sarad1p1ty** [comment]
Hi, I haven't contributed to open source before but would like to give this a go, please?

**Comment by mk-mxp** [comment]
Hi @sarad1p1ty and welcome to the Exercism PHP track! Thank you for wanting to contribute and joining the volunteers.

Do you have experience with PHP and a little bit PHPUnit? You need to read and understand the [tests file of this exercise](https://github.com/exercism/php/blob/main/exercises/concept/annalyns-infiltration/AnnalynsInfiltrationTest.php) so you can extract the logic table.

The problem at hand is a mismatch between the tests and the instructions. We want to keep the tests as they are and adjust the wording of the instructions ([this markdown file](https://github.com/exercism/php/blob/main/exercises/concept/annalyns-infiltration/.docs/instructions.md)).

If you still want to do this:

- Fork this repository and follow GitHub workflow (commit to a branch in your fork)
- Open a Pull Request here mentioning this issue (`#758`)
- Try to solve all the points in the list above, all files to modify are [inside the exercise folder](exercises/concept/annalyns-infiltration)

If we need to discuss the wording, we may use the exercism forum for that. That's because most of us maintainers here are no native speakers and the forum has a broader audience with many more native and non-native english speakers.

Thanks again and don't hesitate to ask if something is unclear.

**Comment by sarad1p1ty** [comment]
Hi @mk-mxp - thank you very much!

I believe I have enough experience with PHP and xUnit type unit testing to be able to do this, yes.

I've created a logic table like so;

Test | Knight Awake | Archer Awake | Prisoner Awake | Dog Present | Can Spy | Can Signal | Can Liberate
-- | -- | -- | -- | -- | -- | -- | --
Everyone Asleep - Dog Present | FALSE | FALSE | FALSE | TRUE | FALSE | FALSE | TRUE
Only Prisoner Awake - Dog Present | FALSE | FALSE | TRUE | TRUE | TRUE | TRUE | TRUE
Only Archer Awake - Dog Present | FALSE | TRUE | FALSE | TRUE | TRUE | FALSE | FALSE
Only Knight Awake - Dog Present | TRUE | FALSE | FALSE | TRUE | TRUE | FALSE | TRUE
Only Prisoner Asleep - Dog Present | TRUE | TRUE | FALSE | TRUE | TRUE | FALSE | FALSE
Only Archer Asleep - Dog Present | TRUE | FALSE | TRUE | TRUE | TRUE | TRUE | TRUE
Only Knight Asleep - Dog Present | FALSE | TRUE | TRUE | TRUE | TRUE | FALSE | FALSE
Everyone Awake - Dog Present | TRUE | TRUE | TRUE | TRUE | TRUE | FALSE | FALSE
Everyone Asleep - No Dog | FALSE | FALSE | FALSE | FALSE | FALSE | FALSE | FALSE
Only Prisoner Awake - No Dog | FALSE | FALSE | TRUE | FALSE | TRUE | TRUE | TRUE
Only Archer Awake - No Dog | FALSE | TRUE | FALSE | FALSE | TRUE | FALSE | FALSE
Only Knight Awake - No Dog | TRUE | FALSE | FALSE | FALSE | TRUE | FALSE | FALSE
Only Prisoner Asleep - No Dog | TRUE | TRUE | FALSE | FALSE | TRUE | FALSE | FALSE
Only Archer Asleep - No Dog | TRUE | FALSE | TRUE | FALSE | TRUE | TRUE | FALSE
Only Knight Asleep - No Dog | FALSE | TRUE | TRUE | FALSE | TRUE | FALSE | FALSE
Everyone Awake - No Dog | TRUE | TRUE | TRUE | FALSE | TRUE | FALSE | FALSE


It's pretty big, but matches all current test cases. Is this what you would like me to add to the markdown file?

It took me a while to understand the issue with the instructions. They seem to match the test cases as they are. As you say on the forum; if Annalyn has her dog, then it only matters whether the Archer is awake or not.

I suppose narratively, there's the question of why - without the dog - the prisoner is startled awake if sleeping and wakes the guards, but doesn't startle and wake the Archer if the dog is present? 
Maybe the dog is extra sneaky? :)

Can I just confirm that we need to work something into the instructions to explain **why** Annalyn **can** rescue the prisoner if the test case states:
```
is_archer_awake: false,
is_prisoner_awake: false,
is_dog_present: true
```
?

Thank you!

**Comment by mk-mxp** [comment]
> I suppose narratively, there's the question of why - without the dog - the prisoner is startled awake if sleeping and wakes the guards, but doesn't startle and wake the Archer if the dog is present?
> Maybe the dog is extra sneaky? :)

I don't remember all the details... If that is the quirk, then maybe the dog is a "well known good friend" of the prisoner, so they instinctively know they are safe? But why should one recognize the dog but not the owner? I'll read into the details again.

The logic table looks great, but columns `Can Spy` and `Can Signal` shouldn't be in that table. As you already made the effort, why not have seperate tables with them (and only the inputs of the functions)? That makes things more clear, I think.

Looking forward to reviewing your PR!

**Comment by mk-mxp** [comment]
@sarad1p1ty

There is `Free prisoner` metioned in the lower part (`## 4.`) of the instructions. That should be `Liberate Prisoner`, too.

I don't see the problem with the tests vs. the instructions anymore. When the dog is *not* present, the only possibility to rescue the prisoner is "prisoner awake", "archer asleep", "knight asleep". With the dog, it does not matter if the prisoner is asleep - as long as the archer is asleep the prisoner can be rescued.

So, maybe: When the dog is present, why is the prisoner not so startled, that the archer has time enough to become ready? Can the dog sneak in without being seen by the knight? And when the prisoner awakes and startles, there is enough time for the prisoner to get away but not for the knight to wake the archer and the archer to get ready?

That seems to make things more weird. I'm not a native english speaker, but to me the description of the instructions is enough to get the function to work.

**Comment by mk-mxp** [comment]
> Can I just confirm that we need to work something into the instructions to explain **why** Annalyn **can** rescue the prisoner if the test case states:
> 
> ```
> is_archer_awake: false,
> is_prisoner_awake: false,
> is_dog_present: true
> ```

@sarad1p1ty I did not answer your question...yes, that's the one that might cause issues in the story.

**Comment by sarad1p1ty** [comment]
Hi @mk-mxp!
Sorry it took me a couple of days to get back to you. Thank you for such thorough feedback!

PR is now done: https://github.com/exercism/php/pull/786

All that's left to do is the actual named task. Are we still changing the instructions?
I got a little confused, I'm afraid. I agree with what you said:

> I don't see the problem with the tests vs. the instructions anymore. When the dog is not present, the only possibility to rescue the prisoner is "prisoner awake", "archer asleep", "knight asleep". With the dog, it does not matter if the prisoner is asleep - as long as the archer is asleep the prisoner can be rescued.

Does changing the instructions to _explicitly_ say that it doesn't matter whether the prisoner is awake when the dog is present make things weirder/more complicated?

I actually am a native English speaker, but that doesn't seem to be helping me right now :)
I've just seen that you've added to the forum post. Can see if there are any ideas there?

**Comment by mk-mxp** [comment]
> Does changing the instructions to _explicitly_ say that it doesn't matter whether the prisoner is awake when the dog is present make things weirder/more complicated?

That sounds like a good idea. Please add that to the Pull Request.

**Comment by mk-mxp** [comment]
> I've just seen that you've added to the forum post. Can see if there are any ideas there?

There were no ideas, just questions about the logic. You could post your Pull Request there, too. Drop the GitHub link into the Reply input and magic happens.

**Comment by mk-mxp** [comment]
Done in #786
