### ISSUE TITLE
#48in24: Sync allergies

### ISSUE THREAD

**Issue by mk-mxp** [exercism/php#761]
- [x] Run `bin/configlet sync -u -e allergies --yes --docs --filepaths --metadata --tests include` (updates the Markdown files and maybe `tests.toml`)
  - docs: instructions unsynced: allergies
  - metadata: unsynced: allergies
- [x] Drop strict types comments from test file and example code (these are useless)
- [x] Add and sync test meta data to tests (`uuid` / `@testdox` in DocBlocks)
- [x] Decide on adding / adjusting / ordering test cases to match current problem specs
  - allergies: missing 1 test case

Do not redesign the student's interface or add test cases that would invalidate existing community solutions. These are extra tasks, which should be discussed in advance.

**Comment by fejan-malek** [comment]
There are Data provider test cases in this exercise, and we also need to change that?

**Comment by mk-mxp** [comment]
See #772 for follow-up
