### ISSUE TITLE
#48in24: knapsack 2024-08-13

### ISSUE THREAD

**Issue by mk-mxp** [exercism/php#782]
- [x] Run `bin/configlet sync -u -e knapsack --yes --docs --filepaths --metadata --tests include` (updates the Markdown files and maybe `tests.toml`)
- [x] Drop strict types comments from test file and example code (these are useless)
- [x] Add and sync test meta data to tests (`uuid` / `@testdox` in DocBlocks)
- [x] Decide on adding / adjusting / ordering test cases to match current problem specs

Do not redesign the student's interface or add test cases that would invalidate existing community solutions. These are extra tasks, which should be discussed in advance.

**Comment by mk-mxp** [comment]
@fejan-malek Do you want to take care of this one?

**Comment by fejan-malek** [comment]
Yes, sure soon I will work on this one. Thanks!

**Comment by mk-mxp** [comment]
@fejan-malek We need that to be merged tomorrow. Do you find time for it or should I do it?

**Comment by fejan-malek** [comment]
@mk-mxp Yes I am little late
