### ISSUE TITLE
Upgrade CI to Ubuntu 24.04

### ISSUE THREAD

**Issue by mk-mxp** [exercism/php#809]
GitHub now [switches to Ubuntu 24.04](https://github.blog/changelog/2024-09-25-actions-new-images-and-ubuntu-latest-changes/), so should we.

**Comment by tomasnorre** [comment]
We simple want to run update all "ubuntu-22.04" references in `.github/workflows` to "ubuntu-24.04"? If so you can assign me, it's done fast.

**Comment by mk-mxp** [comment]
@tomasnorre I think, that's all we need to do.
