### ISSUE TITLE
#48in24: bank-account 2024-10-22

### ISSUE THREAD

**Issue by mk-mxp** [exercism/php#812]
- [x] Run `bin/configlet sync -u -e bank-account --yes --docs --filepaths --metadata --tests include` (updates the Markdown files and maybe `tests.toml`)
  - docs: instructions unsynced: bank-account
  - metadata: unsynced: bank-account
- [x] Drop strict types comments from test file and example code (these are useless)
- [x] Add and sync test meta data to tests (`uuid` / `@testdox` in DocBlocks)
- [x] Decide on adding / adjusting / ordering test cases to match current problem specs
  - bank-account: missing 17 test cases
  - Most likely: the `tests.toml` file is missing, but the tests are there

Do not redesign the student's interface or add test cases that would invalidate existing community solutions. These are extra tasks, which should be discussed in advance.

**Comment by tomasnorre** [comment]
The last test case is not implemented as it's requires concurrent calls. 
https://github.com/exercism/problem-specifications/blob/main/exercises/bank-account/canonical-data.json#L345

**Comment by mk-mxp** [comment]
Yes, concurrency is hard in PHP. We'll not include it.
