### ISSUE TITLE
Ensure deprecated exercises are deprecated

### ISSUE THREAD

**Issue by mk-mxp** [exercism/php#813]
This [forum post](http://forum.exercism.org/t/binary-expected-output-is-not-decimal-representation-of-a-number/13281/2) says that Binary is deprecated for very long, but PHP still has it active.

As deprecating exercises does not do any harm to existing solutions and people currently attempting it, we should ensure, that all deprecated exercises from problem-specifications are marked as deprecated and so not shown to new users.

I'm sure, `configlet` has a command to list those exercises and they can easily be marked deprecated in the central `config.json`.

**Comment by tomasnorre** [comment]
I don't find that command in the `configlet --help` info

**Comment by mk-mxp** [comment]
So it is not an easy task to do. [Feature request filed](https://forum.exercism.org/t/configlet-report-exercises-deprecated-in-problem-specs-but-not-in-track/13286) in forum.

Without a command, scanning problem-specifications and comparing to our central `config.json` is required...
