### ISSUE TITLE
#48in24: diamond 2024-12-03

### ISSUE THREAD

**Issue by mk-mxp** [exercism/php#826]
- [x] Run `bin/configlet sync -u -e diamond --yes --docs --filepaths --metadata --tests include` (updates the Markdown files and maybe `tests.toml`)
  - docs: instructions unsynced: diamond
  - metadata: unsynced: diamond
- [x] Drop strict types comments from test file and example code (these are useless)
- [x] Add and sync test meta data to tests (`uuid` / `@testdox` in DocBlocks)
- [ ] Decide on adding / adjusting / ordering test cases to match current problem specs

Do not redesign the student's interface or add test cases that would invalidate existing community solutions. These are extra tasks, which should be discussed in advance.

**Comment by mk-mxp** [comment]
I don't think renaming the function is worth breaking all existing solutions.

**Comment by tomasnorre** [comment]
> I don't think renaming the function is worth breaking all existing solutions.

I agree.
