### ISSUE TITLE
Sync atbash-cipher

### ISSUE THREAD

**Issue by mk-mxp** [exercism/php#839]
- [x] Run `bin/configlet sync -u -e atbash-cipher --yes --docs --filepaths --metadata --tests include` (updates the Markdown files and maybe `tests.toml`)
  - docs: instructions unsynced: atbash-cipher
- [x] Drop strict types comments from test file and example code (these are useless)
- [x] Add and sync test meta data to tests (`uuid` / `@testdox` in DocBlocks)
- [x] Decide on adding / adjusting / ordering test cases to match current problem specs

Do not redesign the student's interface or add test cases that would invalidate existing community solutions. These are extra tasks, which should be discussed in advance.

**Comment by tomasnorre** [comment]
the `decode()` is currently not implemented in `example.php` so the missing test cases (all for decode()) is logically failing. 

Should `decode()` be added to the `example.php` or left out from the tests?

**Comment by homersimpsons** [comment]
> About adding `decode`: Yes, I think that is worth breaking all existing solutions. @homersimpsons Do you agree?

There are 128 published solutions. So yes let's add `decode`.
