### ISSUE TITLE
Sync book-store

### ISSUE THREAD

**Issue by mk-mxp** [exercism/php#842]
- [x] Run `bin/configlet sync -u -e book-store --yes --docs --filepaths --metadata --tests include` (updates the Markdown files and maybe `tests.toml`)
  - docs: instructions unsynced: book-store
- [x] Drop strict types comments from test file and example code (these are useless)
- [x] Add and sync test meta data to tests (`uuid` / `@testdox` in DocBlocks)
- [x] Decide on adding / adjusting / ordering test cases to match current problem specs
  - book-store: missing 3 test cases

Do not redesign the student's interface or add test cases that would invalidate existing community solutions. These are extra tasks, which should be discussed in advance.

**Comment by mk-mxp** [comment]
OK, this exercise has some complicated issues...

1. The canonical data states "implementors should use proper fixed-point or currency data types of the corresponding language and not float." Our implementation currently uses `float`. We may opt to use `int` and cents as the canonical test data contains them already or continue using `float`.
2. `assertEquals()` is not appropriate for float values. There is `assertEqualsWithDelta()` for floating point comparison. This might already make the current example code pass the tests.
3. The missing tests seem to be those that "optimize" the price for cases with 5 different books but a group of 5 is not the optimum. I do not know the history of the exercise, but these seem to be added to catch edge cases of optimizing. I think we should have them.

Any additional findings / thoughts?

**Comment by tomasnorre** [comment]
My 5cents.

1. I would go for `int` as that is the right way to handle amount in PHP, if not using a money library. 

2. The `assertEqualsWithDelta()` would not be needed then. 

3. I think we should include all test cases, en ever exercise, unless there are some functionality in PHP making it super hard or impossible. 

I have forgotten have to look up how many people have already solved the exercise, and how many it would break for.

**Comment by homersimpsons** [comment]
> @homersimpsons Your opinion about 1. / 2.? Proper float comparison or using int instead?

I know I always prefer `int` for monetary values. I think it is a good way to show students that this could be used and avoids most rounding issues. It may helps them in the future too when they wil handle monetary values.

I would prefer to avoid float here. Another alternative could be to use [BCMath](https://www.php.net/manual/en/book.bc.php).

So my vote is (from most preferred to least preferred) `int` > `bcmath` >> `float`.

> There is 61 solutions, only ~40% of 153 people who tried this. So this should be improved.

61 solutions looks fine for me to change this completely.

**Comment by mk-mxp** [comment]
OK, thanks everybody. We agreed on `int` and as we break existing solutions with that we will have all test cases with exactly the data from canonical data. @tomasnorre please continue with the PR.

**Comment by tomasnorre** [comment]
I'll take care tomorrow or beginning of next week.
