### ISSUE TITLE
Sync darts

### ISSUE THREAD

**Issue by mk-mxp** [exercism/php#853]
- [x] Run `bin/configlet sync -u -e darts --yes --docs --filepaths --metadata --tests include` (updates the Markdown files and maybe `tests.toml`)
  - docs: instructions unsynced: darts
  - metadata: unsynced: darts
- [x] Drop strict types comments from test file and example code (these are useless)
- [x] Add and sync test meta data to tests (`uuid` / `@testdox` in DocBlocks)
- [x] Decide on adding / adjusting / ordering test cases to match current problem specs
  - darts: missing 13 test cases

Do not redesign the student's interface or add test cases that would invalidate existing community solutions. These are extra tasks, which should be discussed in advance.

**Comment by mk-mxp** [comment]
I think we need a complete re-make of this exercise...

* Nothing object-oriented to do here
* Uses a public property to present the result
* Does all the work in the constructor
* Not all inputs are floats but should be

I suggest using a simple function for this exercise:

```php
declare(strict_types=1);

function score(float $xAxis, float $yAxis): int
{
    throw new BadFunctionCallException('Please implement the "' . __FUNCTION__ . '" function!');
}
```

In the tests we should use float notation instead of mixing integers and floats:

```php
    public function testMissedTarget(): void
    {
        $this->assertSame(0, score(-9.0, 9.0));
    }
```

This would break 96 existing solutions, but improve the exercise a lot. Opinions?

@homersimpsons @tomasnorre

**Comment by homersimpsons** [comment]
> Nothing object-oriented to do here

It makes sense to use a simple function for this. But I think it depends on the "difficulty" we want here. I find it rare in PHP applications nowadays to have a non-OOP approach. I am OK with both approach.

> Uses a public property to present the result

I agree that this should be avoided

> Does all the work in the constructor

I agree that this should be avoided

> Not all inputs are floats but should be

I agree that they should all have the same type
