### ISSUE TITLE
Suggestion for additional test

### ISSUE THREAD

**Issue by dexmexter** [exercism/php#858]
I think there is a specific test case that could be added to this file to improve the testing coverage: https://github.com/exercism/php/blob/1df6486b88f85a77387f25fb2d97db8fbf98f967/exercises/practice/matching-brackets/MatchingBracketsTest.php

I do not know what the procedure for making this type of change is and would be happy to read through any documentation if I am missing some crutial step. Here is the test I would propose:

```php
/**
 * uuid [ not sure how this is generated ]
 * @testdox Nested followed by pair
 */
public function testNestedThenPair(): void
{
    $this->assertTrue(brackets_match("if (foo[1] === 0){return true;}"));
}
```

The way I discovered this is that my original approach was only considering matching brackets from the outside-in (eg. `[({})]`), or matching pairs that are side-by-side (eg. `()[]{}`). I knew this was a limited approach and expected to have some tests fail and was surprised that everything passed. 

If there is some way I could contribute further to help get this (or something like it) included, I would enjoy slowly working through the process of learning how to submit a formal PR (or whatever process precedes that step). I do not wish to cause any annoyance though and understand that dealing with a very inexperienced individual is not always desirable.

**Comment by mk-mxp** [comment]
Thanks for raising this issue. There is many things to say about that, in short:
* Suggestions for additional tests in practice exercises should be discussed in the Discord forum
* All tests come from a central repository and are used by 70+ tracks
* Tests intentionally do not cover all edge cases

Looking forward to join the discussion in the forum!

**Comment by dexmexter** [comment]
Thanks, I'll have a look over at the forum. I must admit that when I first read the message a saw "Discord", I felt a bit deflated because I did not look forward to the noise/chaos that tends to categorize Discord conversations. I'm very encouraged by your edit though because I think a forum is is a much better place for this type of discussion. 

Please let me know if I should close this ticket in the meantime (or feel free to close it on my behalf).

**Comment by dexmexter** [comment]
I discovered that someone else had already brought up the same point in the python track and the conversation didn't get very far. I've chosen to add a comment to the existing topic, rather than create another that would likely be viewed as a duplicate. https://forum.exercism.org/t/additional-test-case-to-matching-brackets/10295/6
