### ISSUE TITLE
Commit broken Unit Tests on MacOS but failed silently

### ISSUE THREAD

**Issue by tomasnorre** [exercism/php#859]
This commit https://github.com/exercism/php/commit/1df6486b88f85a77387f25fb2d97db8fbf98f967 broken the unit tests on MacOS, but fails silently, so I saw it by coincidence. 

Will focus on this before adding more PRs for the Sync Exercises.

![Screenshot From 2024-11-14 19-06-06](https://github.com/user-attachments/assets/3e0969a9-8e92-44c0-985f-154e11481f0e)

**Comment by mk-mxp** [comment]
Maybe add `local -a name_filter` before `name_filter=()`? This makes the variable name a) local scoped and b) known as an array even when not filled. If that doesn't help, replace `name_filter=()` with `name_filter=( " " ) # MacOS otherwise sees unbound variable` or similar.

**Comment by tomasnorre** [comment]
> Maybe add `local -a name_filter` before `name_filter=()`? This makes the variable name a) local scoped and b) known as an array even when not filled. If that doesn't help, replace `name_filter=()` with `name_filter=( " " ) # MacOS otherwise sees unbound variable` or similar.

Will check it out later. I have an older macbook, that I might be able to test it on locally.
